name: AnimeBoard
version: 2.0.0 SNAPSHOT
main: com.justdoom.animeboard.AnimeBoard
api-version: 1.17
authors: [ JustDoom ]
softdepend:
  - PlaceHolderAPI
commands:
  animeboard:
    aliases: ab
    permission: animeboard

permissions:
  animeboard:
    default: op