name: AnimeBoard
version: 1.12 Beta
main: com.imjustdoom.animeboard.AnimeBoard
api-version: 1.13
authors: [ JustDoom ]
load: POSTWORLD
softdepend:
  - BetterReload
  - PlaceHolderAPI
  - packetevents
commands:
  animeboard:
    aliases: ab
    permission: animeboard

permissions:
  animeboard:
    default: op