name: AnimeBoard
version: 1.12 Beta
main: com.imjustdoom.animeboard.AnimeBoard
api-version: 1.13
authors: [ JustDoom ]
softdepend:
  - PlaceHolderAPI
commands:
  animeboard:
    aliases: ab
    permission: animeboard

permissions:
  animeboard:
    default: op